using MikuMikuLibrary.Hashes;
using VRoidDiva.Diva;
using VRoidDiva.Retarget;
using VRoidDiva.Vrm;

namespace VRoidDiva;

/// <summary>Everything one conversion needs. Null IDs are derived from the module name.</summary>
public sealed class ConvertRequest
{
    public string VrmPath { get; set; }
    public string OutputDirectory { get; set; }
    public List<string> References { get; set; } = new();
    public List<string> CpkEntries { get; set; } = new();

    public string Name { get; set; }
    public string Character { get; set; } = "MIKU";
    public string Author { get; set; }
    public int? ModuleId { get; set; }
    public int? ItemNumber { get; set; }
    public int? Costume { get; set; }
    public int? ObjectSetId { get; set; }
    public int? SortIndex { get; set; }

    public string BoneMapPath { get; set; }
    public int MaxTextureSize { get; set; } = 2048;
    public float Scale { get; set; } = 1.0f;
    public bool NoStretch { get; set; }
    public bool AllCloth { get; set; }
}

public sealed class ConvertResult
{
    public string DisplayName { get; init; }
    public ModuleDefinition Module { get; init; }
    public int ObjectSetId { get; init; }
    public IReadOnlyList<string> WrittenFiles { get; init; }
    public IReadOnlyList<string> Warnings { get; init; }
}

/// <summary>The whole VRM → mod pipeline, shared by the command line and the window app.</summary>
public static class Converter
{
    public static ConvertResult Run(ConvertRequest request, Action<string> log = null)
    {
        log ??= _ => { };

        if (string.IsNullOrWhiteSpace(request.VrmPath))
            throw new ArgumentException("No .vrm file was chosen.");
        if (string.IsNullOrWhiteSpace(request.OutputDirectory))
            throw new ArgumentException("No output folder was chosen.");
        if (request.References.Count == 0)
            throw new ArgumentException("A reference is required (a stock character object set from the game).");

        log($"Reading {request.VrmPath}");
        var model = VrmModel.Load(request.VrmPath);
        log($"  VRM {model.SpecVersion}: {model.Primitives.Count} primitives, " +
            $"{model.Materials.Count} materials, {model.HumanBones.Count} humanoid bones");

        var skeleton = LoadReferences(request.References, request.CpkEntries, log);

        var boneMap = BoneMap.CreateDefault();
        if (!string.IsNullOrEmpty(request.BoneMapPath))
            boneMap.ApplyOverrides(request.BoneMapPath);

        log("Fitting the model to the DIVA skeleton");
        var retarget = Retargeter.Retarget(model, skeleton, boneMap, new RetargetOptions
        {
            FitLimbLengths = !request.NoStretch,
            ExtraScale = request.Scale
        });
        foreach (string warning in retarget.Warnings)
            log($"  warning: {warning}");
        log($"  {retarget.Mapping.Count} humanoid bones mapped onto {retarget.Bones.Count} DIVA bones " +
            $"(scale {retarget.Scale:F3})");

        var character = Diva.Character.Find(request.Character ?? "MIKU");
        string displayName = !string.IsNullOrWhiteSpace(request.Name)
            ? request.Name.Trim()
            : DefaultName(model, request.VrmPath);
        var ids = DefaultIds(displayName);

        int moduleId = request.ModuleId ?? ids.ModuleId;
        int itemNumber = request.ItemNumber ?? moduleId;
        int costume = request.Costume ?? ids.Costume;
        int objectSetId = request.ObjectSetId ?? ids.ObjectSetId;

        if (objectSetId is < 1 or > 0xFFFF)
            throw new ArgumentException("The object set ID must be between 1 and 65535 (the game stores it as 16 bits).");

        string objectSetName = $"{character.Prefix}ITM{itemNumber}";
        var module = new ModuleDefinition
        {
            Character = character,
            ModuleId = moduleId,
            CostumeNumber = costume,
            ItemNumber = itemNumber,
            SortIndex = request.SortIndex ?? moduleId,
            DisplayName = displayName,
            ObjectSetName = objectSetName,
            BodyObjectName = $"{objectSetName}_BODY_VRM",
            DummyObjectName = $"{objectSetName}_HIDDEN"
        };

        log("Building the DIVA object set");
        var objectSet = ObjectBuilder.Build(model, retarget, objectSetName, module.BodyObjectName,
            module.DummyObjectName, new ObjectBuildOptions
            {
                MaxTextureSize = request.MaxTextureSize,
                AllCloth = request.AllCloth
            });

        var info = new ModInfo
        {
            Name = displayName,
            Author = request.Author ?? model.Author ?? "",
            Description = $"VRoid model '{displayName}' as a {character.ModuleName} module (generated by VRoidDiva)."
        };

        var written = ModWriter.Write(request.OutputDirectory, objectSet, (uint)objectSetId, module, info);

        log("");
        log($"Module '{displayName}' written to {Path.GetFullPath(request.OutputDirectory)}");
        log($"  character {character.ModuleName}, module ID {moduleId}, COS_{costume:D3}, " +
            $"item {itemNumber}, object set {objectSetName} (ID {objectSetId})");
        foreach (string path in written)
            log($"  {Path.GetRelativePath(request.OutputDirectory, path)}");

        return new ConvertResult
        {
            DisplayName = displayName,
            Module = module,
            ObjectSetId = objectSetId,
            WrittenFiles = written,
            Warnings = retarget.Warnings
        };
    }

    public static string DefaultName(VrmModel model, string vrmPath) =>
        !string.IsNullOrWhiteSpace(model.Title) ? model.Title.Trim() : Path.GetFileNameWithoutExtension(vrmPath);

    /// <summary>IDs derived from the module name, so the same name always gives the same IDs.</summary>
    public static (int ModuleId, int Costume, int ObjectSetId) DefaultIds(string displayName)
    {
        uint hash = MurmurHash.Calculate(displayName);
        return (4000 + (int)(hash % 5000), 600 + (int)(hash / 7 % 399), 40000 + (int)(hash / 13 % 25000));
    }

    public static ReferenceSkeleton LoadReferences(IEnumerable<string> paths, IReadOnlyList<string> cpkEntries,
        Action<string> log)
    {
        var skeleton = new ReferenceSkeleton();
        foreach (string path in paths)
        {
            log($"Reading reference skeleton from {path}");
            skeleton.LoadFrom(path, cpkEntries, log);
        }

        if (skeleton.Bones.Count == 0)
            throw new InvalidDataException("No skinned objects were found in the reference object set(s).");

        log($"  {skeleton.Bones.Count} bones from {skeleton.LoadedObjects.Count} skinned objects");
        return skeleton;
    }
}
