<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VRoidDivaCli</AssemblyName>
    <RootNamespace>VRoidDiva</RootNamespace>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\MikuMikuLibrary\MikuMikuLibrary\MikuMikuLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VRoidDiva.Tests" />
  </ItemGroup>

</Project>
